version: '2'
services:

 #Portainer - WebUI for Containers
  portainer:
    image: portainer/portainer
    hostname: portainer
    container_name: PortainerTeST
    restart: always
    ports:
      - "9001:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/nfs/docker_config/Portainer/data:/data

# Organizer - Unified HTPC/Home Server Web Interface
  organizr:
    container_name: organizr
    hostname: organizr
    restart: always
    image: lsiocommunity/organizr
    volumes:
      - /mnt/nfs/docker_config/Organizer/config:/config
    ports:
      - "8085:80"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
